spring.datasource.url=jdbc:postgresql://localhost:5432/cp_tracker
spring.datasource.username=krishna
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080